name: Node_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Maven packaging
      run: mvn -B clean package --file pom.xml
    - name: Set target as work directory
      run: |
          cd target
          ls
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
          context: .
          push: true
          tags: v1
          labels: node
#    - name: Build Docker ima#ge
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
#       image: node
#       registry: docker.io
#       dockerfile: 'target/Dockerfile'
#       username: ${{ secrets.DOCKER_USERNAME }}
#       password: ${{ secrets.DOCKER_PASSWORD }}
